In [4]:
import pandas as pd
import scipy as sp
import numpy as np

filepath = 'https://raw.githubusercontent.com/selva86/datasets/master/diamonds.csv'
df = pd.read_csv(filepath).iloc[:, [0,4,6]]
df.head()

carat  depth  price
0   0.23   61.5    326
1   0.21   59.8    326
2   0.23   56.9    327
3   0.29   62.4    334
4   0.31   63.3    335

In [5]:
from scipy.linalg import inv

In [30]:
def mahalanobis(x=None, data=None, cov=None):
    """Compute the Mahalanobis Distance between each row of x and the data  
    x    : vector or matrix of data with, say, p columns.
    data : ndarray of the distribution from which Mahalanobis distance of each observation of x is to be computed.
    cov  : covariance matrix (p x p) of the distribution. If None, will be computed from data.
    """
    x_minus_mu = x - np.mean(data)
    if not cov:
        cov = np.cov(data.values.T)
    inv_covmat = sp.linalg.inv(cov)
    left_term = np.dot(x_minus_mu, inv_covmat)
    mahal = np.dot(left_term, x_minus_mu.T)
    return mahal.diagonal()

df_x = df[['carat', 'depth', 'price']].head(500)
df_x['mahala'] = mahalanobis(x=df_x, data=df[['carat', 'depth', 'price']])
df_x.head()


carat  depth  price     mahala
0   0.23   61.5    326   1.709860
1   0.21   59.8    326   3.540097
2   0.23   56.9    327  12.715021
3   0.29   62.4    334   1.454469
4   0.31   63.3    335   2.347239

In [33]:
(df - np.mean(df)).shape

(53940, 3)

In [34]:
a = df.values.T
a_cov = np.cov(a)
print(a_cov)
b = np.linalg.inv(a_cov)
print('\n')
print(b)

print('\n',sp.linalg.inv(a_cov))

[[ 2.24686660e-01  1.91665282e-02  1.74276536e+03]
 [ 1.91665282e-02  2.05240384e+00 -6.08537121e+01]
 [ 1.74276536e+03 -6.08537121e+01  1.59156294e+07]]


[[ 2.98255446e+01 -3.75404629e-01 -3.26733989e-03]
 [-3.75404629e-01  4.92013886e-01  4.29881243e-05]
 [-3.26733989e-03  4.29881243e-05  4.20770213e-07]]

 [[ 2.98255446e+01 -3.75404629e-01 -3.26733989e-03]
 [-3.75404629e-01  4.92013886e-01  4.29881243e-05]
 [-3.26733989e-03  4.29881243e-05  4.20770213e-07]]


In [11]:
np.mean(df[['carat', 'depth', 'price']])

carat       0.797940
depth      61.749405
price    3932.799722
dtype: float64

In [13]:
np.mean(df)

carat       0.797940
depth      61.749405
price    3932.799722
dtype: float64

In [7]:
df.shape

(53940, 3)

In [12]:
df.head()

carat  depth  price
0   0.23   61.5    326
1   0.21   59.8    326
2   0.23   56.9    327
3   0.29   62.4    334
4   0.31   63.3    335

In [13]:
df_x.shape

(500, 4)

In [15]:
df_x.head()

carat  depth  price     mahala
0   0.23   61.5    326   1.709860
1   0.21   59.8    326   3.540097
2   0.23   56.9    327  12.715021
3   0.29   62.4    334   1.454469
4   0.31   63.3    335   2.347239

In [16]:
data=df[['carat', 'depth', 'price']]
data.shape

(53940, 3)

In [17]:
data.head()

carat  depth  price
0   0.23   61.5    326
1   0.21   59.8    326
2   0.23   56.9    327
3   0.29   62.4    334
4   0.31   63.3    335